language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t dmitrymishanov/docker-react .

script:
  - docker run -e CI=true dmitrymishanov/docker-react npm run test